---
- name: demo playbook
  hosts: all
  gather_facts: no
  connection: local
  
  tasks:
  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "netscript"
        password: "sgcib123"

  - name: IOS | Show clock
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show version
    register: version
     
  - name: Check OS
    command: ansible --version
    register: ansiblev
    when: "'nxos.7.0.3.I4.1.bin' in version"
    
  - debug: msg="{{ version.stdout }}"  
  - debug: msg="{{ ansiblev.stdout }}"
