---
- name: demo playbook
  hosts: all
  gather_facts: no
  connection: local
  
  tasks:
  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "netscript"
        password: "sgcib123"
        
  - name: Gather Show Version Facts
    nxos_command:
      commands:
        - show version
      output: json
      provider: "{{ provider }}"    
    register: showvers

  - debug: msg="{{ showvers.stdout_lines }}"
