---
- name: demo playbook
  hosts: all
  gather_facts: no
  connection: local
  
  vars:
   Current_Version: 7.0(3)I4(1)

  tasks:
  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        transport: nxapi
        username: "netscript"
        password: "sgcib123"
        
  - name: Gather Show Version Facts
    nxos_command:
      commands:
        - show version
      provider: "{{ provider }}"    
    register: showvers

  - set_fact: perform_upgrade={{ Current_Version in showvers['stdout'][0]['kickstart_ver_str'] }}

  - name: Check NXOS Version
    assert:
      that:
        - "'{{ Current_Version }}' in showvers['stdout'][0]['kickstart_ver_str']"
        
  - name: Configuration before upgrade 
    nxos_command:
      commands:
        - show running
      provider: '{{ provider }}'
    when: perform_upgrade

  - debug: msg="{{ showvers.stdout_lines }}"
