---
- name: demo playbook
  hosts: all
  gather_facts: no
  connection: local
  
  vars:
   Current_Version: 7.0(3)I4(1)

  tasks:
  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        transport: nxapi
        username: "netscript"
        password: "sgcib123"
        
  - name: Gather Show Version Facts
    nxos_command:
      commands:
        - show version
      provider: "{{ provider }}"    
    register: showvers

  - name: Check NXOS Version
    assert:
      that:
        - "'0{{ Current_Version }}' in showvers['stdout'][0]['kickstart_ver_str']"

  - debug: msg="{{ showvers.stdout_lines }}"
