---
- name: demo playbook
  hosts: all
  gather_facts: no
  connection: local
  
  vars:
   morning_check:
     - show version
     - show clock
     - show ip int br
  
  tasks:
  
  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "netscript"
        password: "sgcib123"
  
  - name: run show version on remote devices
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show version
    register: version

  - name: run multiple show on remote devices
    cisco_ios_show:
      provider: "{{ provider }}"
      commands: "{{ morning_check }}"
    register: check

  - debug: msg="{{ version.stdout }}"
  - debug: msg="{{ check.stdout }}"
