---
- name: demo playbook
  hosts: all
  gather_facts: no
  connection: local
  
  vars:
  cli:
    host: "{{ inventory_hostname }}"
    username: netscript
    password: sgcib123
    transport: cli
  
  tasks:
    - name: show version
      eos_command:
        commands: show version
        provider: "{{ eapi }}"
      register: output
        
    - name: output to stdout
      debug: var=output.stdout_lines[0]
